import { NextResponse } from 'next/server';
import { genaiClient } from '@/lib/gemini';
import { readFile, writeFile } from 'fs/promises';
import path from 'path';

export async function POST(request) {
    try {
        const { imagePath, instructions } = await request.json();

        if (!imagePath || !instructions) {
            return NextResponse.json({ error: 'Missing imagePath or instructions' }, { status: 400 });
        }

        const absoluteInputPath = path.join(process.cwd(), 'public', imagePath);
        const filename = path.basename(imagePath);
        const ext = path.extname(filename);
        const nameWithoutExt = path.basename(filename, ext);
        const timestamp = Date.now();
        const outputFilename = `enhanced-${timestamp}-${nameWithoutExt}.png`; // Always PNG for generative output
        const absoluteOutputPath = path.join(process.cwd(), 'public/processed', outputFilename);
        const publicOutputPath = `/processed/${outputFilename}`;

        // 1. Read input image
        const imageBuffer = await readFile(absoluteInputPath);
        const imageBase64 = imageBuffer.toString('base64');

        // 2. Call Gemini 3 Pro for Image Editing
        console.log(`[Gemini 3] Processing: ${filename}`);

        const response = await genaiClient.models.generateContent({
            model: 'gemini-3-pro-image-preview',
            contents: [
                {
                    role: 'user',
                    parts: [
                        { text: `Edit this image. Instructions: ${instructions}. Maintain photorealism. High quality real estate photography.` },
                        {
                            inlineData: {
                                mimeType: ext === '.png' ? 'image/png' : 'image/jpeg',
                                data: imageBase64
                            }
                        }
                    ]
                }
            ],
            config: {
                responseModalities: ['IMAGE'],
                imageConfig: {
                    aspectRatio: "16:9",
                    imageSize: "4k"
                }
            }
        });

        // 3. Handle Generated Image Response
        const candidate = response.candidates?.[0];
        if (!candidate || !candidate.content || !candidate.content.parts) {
            throw new Error("No image generated by Gemini 3.");
        }

        let imageSaved = false;

        for (const part of candidate.content.parts) {
            if (part.inlineData && part.inlineData.data) {
                // Save the base64 image data to file
                const buffer = Buffer.from(part.inlineData.data, 'base64');
                await writeFile(absoluteOutputPath, buffer);
                imageSaved = true;
                break;
            }
        }

        if (!imageSaved) {
            throw new Error("Gemini response contained no image data.");
        }

        console.log(`[Success] Saved to ${absoluteOutputPath}`);

        return NextResponse.json({
            success: true,
            originalPath: imagePath,
            enhancedPath: publicOutputPath
        });

    } catch (error) {
        console.error('Enhance API (Gemini 3) Error:', error);
        return NextResponse.json({
            error: 'AI Enhancement Failed',
            details: error.message
        }, { status: 500 });
    }
}
